version: '3'
services:
  app:
    build: ./app
    container_name: app
    ports:
        - '3001:3001'
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5436:5436"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
